<?php

namespace keijoCMS\Core;

require_once dirname(__FILE__) . '/../../../Core/Request.php';

/**
 * Test class for Request.
 * Generated by PHPUnit on 2012-07-07 at 00:50:52.
 */
class RequestTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Request
     */
    protected $object;

    protected $defualtPost = array('not' => 'empty');
    protected $defualtGet = array('nor' => 'this');
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $_GET = $this->defualtGet;
        $_POST = $this->defualtPost;

        $this->object = new Request();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers keijoCMS\Core\Request::__contstruct
     */
    public function test__construct()
    {
        $this->assertObjectHasAttribute('postParams', $this->object);
        $this->assertObjectHasAttribute('getParams', $this->object);
        $this->assertObjectHasAttribute('requestParams', $this->object);

        $this->assertEmpty($_POST, 'POST not cleared');
        $this->assertEmpty($_GET, 'GET not cleared');
    }

    /**
     * @covers keijoCMS\Core\Request::post
     */
    public function testPost()
    {
        //Post without index should return whole defaultPost
        $this->assertEquals($this->defualtPost, $this->object->post());
        //Post with index should return same index from defaultPost
        $this->assertEquals($this->defualtPost['not'], $this->object->post('not'));
        
        //Post with non-existing index should return NULL
        $this->assertEquals(null, $this->object->post('non existing'));
    }

}

function D()
{
    $arguments = func_get_args();
    echo "\n";
    foreach ($arguments as $arg)
        var_dump($arg);
}